export const CURATED_ATTACK_PRESETS_BY_FAMILY = {
  blade: [
    {
      id: "blade_saber_wave",
      label: "Saber Wave",
      prompt: "Swing-cast a bright saber wave with a clean forward slash.",
      attack: {
        description: "Saber Wave",
        family: "blade",
        deliveryStyle: "swing",
        palette: { primaryColor: "#fb923c", accentColor: "#fde68a" },
        weaponVisual: { kind: "saber", primaryColor: "#fb923c", accentColor: "#fde68a", scale: 1.15, handOffsetX: 0.2, handOffsetY: 0 },
        castFx: { color: "#fde68a", accentColor: "#fb923c", count: 8, sizeScale: 0.45, speedScale: 1.6, lifespan: 0.22 },
        actions: [
          {
            type: "projectiles",
            pattern: "straight",
            projectileKind: "shard",
            count: 1,
            speed: 13,
            sizeScale: 0.68,
            spreadDeg: 0,
            damageScale: 1,
            lifetimeFrames: 42,
            gravityScale: 0,
            homingStrength: 0,
            orbitFrames: 0,
            orbitRadiusScale: 1,
            waveAmplitudeScale: 0,
            waveFrequency: 0,
            beamLengthScale: 0,
            beamWidthScale: 0,
            knockback: 5,
            color: "#fb923c",
            accentColor: "#fde68a",
            splashRadiusScale: 0,
            splashDamageScale: 0.7,
          },
        ],
      },
    },
    {
      id: "blade_twin_chakrams",
      label: "Twin Chakrams",
      prompt: "Swing-cast twin glowing chakrams that fan outward.",
      attack: {
        description: "Twin Chakrams",
        family: "blade",
        deliveryStyle: "swing",
        palette: { primaryColor: "#f97316", accentColor: "#fff7ed" },
        weaponVisual: { kind: "chakram", primaryColor: "#f97316", accentColor: "#fff7ed", scale: 1, handOffsetX: 0.1, handOffsetY: 0 },
        castFx: { color: "#fff7ed", accentColor: "#f97316", count: 6, sizeScale: 0.4, speedScale: 1.4, lifespan: 0.18 },
        actions: [
          {
            type: "projectiles",
            pattern: "spread",
            projectileKind: "chakram",
            count: 2,
            speed: 12,
            sizeScale: 0.72,
            spreadDeg: 18,
            damageScale: 0.95,
            lifetimeFrames: 56,
            gravityScale: 0,
            homingStrength: 0,
            orbitFrames: 0,
            orbitRadiusScale: 1,
            waveAmplitudeScale: 0,
            waveFrequency: 0,
            beamLengthScale: 0,
            beamWidthScale: 0,
            knockback: 4,
            color: "#f97316",
            accentColor: "#fff7ed",
            splashRadiusScale: 0,
            splashDamageScale: 0.7,
          },
        ],
      },
    },
  ],
  ballistic: [
    {
      id: "ballistic_sidearm",
      label: "Sidearm Shot",
      prompt: "Punch-fired sidearm shot with a fast clean tracer.",
      attack: {
        description: "Sidearm Shot",
        family: "ballistic",
        deliveryStyle: "punch",
        palette: { primaryColor: "#38bdf8", accentColor: "#f8fafc" },
        weaponVisual: { kind: "pistol", primaryColor: "#38bdf8", accentColor: "#f8fafc", scale: 1, handOffsetX: 0.15, handOffsetY: 0 },
        castFx: { color: "#f8fafc", accentColor: "#38bdf8", count: 6, sizeScale: 0.36, speedScale: 1.8, lifespan: 0.16 },
        actions: [
          {
            type: "projectiles",
            pattern: "straight",
            projectileKind: "bullet",
            count: 1,
            speed: 15,
            sizeScale: 0.45,
            spreadDeg: 0,
            damageScale: 1,
            lifetimeFrames: 46,
            gravityScale: 0,
            homingStrength: 0,
            orbitFrames: 0,
            orbitRadiusScale: 1,
            waveAmplitudeScale: 0,
            waveFrequency: 0,
            beamLengthScale: 0,
            beamWidthScale: 0,
            knockback: 6,
            color: "#38bdf8",
            accentColor: "#f8fafc",
            splashRadiusScale: 0,
            splashDamageScale: 0.7,
          },
        ],
      },
    },
    {
      id: "ballistic_scatter",
      label: "Scatter Burst",
      prompt: "Punch-cast a short scatter burst from a compact rifle.",
      attack: {
        description: "Scatter Burst",
        family: "ballistic",
        deliveryStyle: "punch",
        palette: { primaryColor: "#0ea5e9", accentColor: "#e0f2fe" },
        weaponVisual: { kind: "rifle", primaryColor: "#0ea5e9", accentColor: "#e0f2fe", scale: 1.08, handOffsetX: 0.18, handOffsetY: 0 },
        castFx: { color: "#e0f2fe", accentColor: "#0ea5e9", count: 8, sizeScale: 0.42, speedScale: 2, lifespan: 0.18 },
        actions: [
          {
            type: "projectiles",
            pattern: "spread",
            projectileKind: "bullet",
            count: 3,
            speed: 13,
            sizeScale: 0.38,
            spreadDeg: 20,
            damageScale: 0.7,
            lifetimeFrames: 34,
            gravityScale: 0,
            homingStrength: 0,
            orbitFrames: 0,
            orbitRadiusScale: 1,
            waveAmplitudeScale: 0,
            waveFrequency: 0,
            beamLengthScale: 0,
            beamWidthScale: 0,
            knockback: 4,
            color: "#0ea5e9",
            accentColor: "#e0f2fe",
            splashRadiusScale: 0,
            splashDamageScale: 0.7,
          },
        ],
      },
    },
  ],
  arcane: [
    {
      id: "arcane_rune_beam",
      label: "Rune Beam",
      prompt: "Swing-cast a focused rune beam from a glowing staff.",
      attack: {
        description: "Rune Beam",
        family: "arcane",
        deliveryStyle: "swing",
        palette: { primaryColor: "#8b5cf6", accentColor: "#67e8f9" },
        weaponVisual: { kind: "staff", primaryColor: "#8b5cf6", accentColor: "#67e8f9", scale: 1.08, handOffsetX: 0.18, handOffsetY: 0 },
        castFx: { color: "#67e8f9", accentColor: "#8b5cf6", count: 10, sizeScale: 0.52, speedScale: 1.7, lifespan: 0.22 },
        actions: [
          {
            type: "beam",
            pattern: "beam",
            projectileKind: "beamlet",
            count: 1,
            speed: 0,
            sizeScale: 0,
            spreadDeg: 0,
            damageScale: 1.05,
            lifetimeFrames: 22,
            gravityScale: 0,
            homingStrength: 0,
            orbitFrames: 0,
            orbitRadiusScale: 0,
            waveAmplitudeScale: 0,
            waveFrequency: 0,
            beamLengthScale: 9.5,
            beamWidthScale: 0.9,
            knockback: 7,
            color: "#8b5cf6",
            accentColor: "#67e8f9",
            splashRadiusScale: 0,
            splashDamageScale: 0,
          },
        ],
      },
    },
    {
      id: "arcane_orb_bolt",
      label: "Arc Orb",
      prompt: "Punch-cast a bright arcane orb with a sharp magical streak.",
      attack: {
        description: "Arc Orb",
        family: "arcane",
        deliveryStyle: "punch",
        palette: { primaryColor: "#a78bfa", accentColor: "#22d3ee" },
        weaponVisual: { kind: "wand", primaryColor: "#a78bfa", accentColor: "#22d3ee", scale: 1, handOffsetX: 0.12, handOffsetY: 0 },
        castFx: { color: "#22d3ee", accentColor: "#a78bfa", count: 7, sizeScale: 0.44, speedScale: 1.5, lifespan: 0.2 },
        actions: [
          {
            type: "projectiles",
            pattern: "straight",
            projectileKind: "orb",
            count: 1,
            speed: 11,
            sizeScale: 0.62,
            spreadDeg: 0,
            damageScale: 0.95,
            lifetimeFrames: 50,
            gravityScale: 0,
            homingStrength: 0.02,
            orbitFrames: 0,
            orbitRadiusScale: 1,
            waveAmplitudeScale: 0,
            waveFrequency: 0,
            beamLengthScale: 0,
            beamWidthScale: 0,
            knockback: 5,
            color: "#a78bfa",
            accentColor: "#22d3ee",
            splashRadiusScale: 0,
            splashDamageScale: 0.7,
          },
        ],
      },
    },
  ],
  explosive: [
    {
      id: "explosive_rocket",
      label: "Micro Rocket",
      prompt: "Punch-fired micro rocket with a bright exhaust trail.",
      attack: {
        description: "Micro Rocket",
        family: "explosive",
        deliveryStyle: "punch",
        palette: { primaryColor: "#f97316", accentColor: "#fde047" },
        weaponVisual: { kind: "launcher", primaryColor: "#f97316", accentColor: "#fde047", scale: 1.1, handOffsetX: 0.18, handOffsetY: 0 },
        castFx: { color: "#fde047", accentColor: "#f97316", count: 8, sizeScale: 0.46, speedScale: 1.8, lifespan: 0.18 },
        actions: [
          {
            type: "projectiles",
            pattern: "lob",
            projectileKind: "rocket",
            count: 1,
            speed: 9,
            sizeScale: 0.58,
            spreadDeg: 0,
            damageScale: 1,
            lifetimeFrames: 58,
            gravityScale: 0.58,
            homingStrength: 0,
            orbitFrames: 0,
            orbitRadiusScale: 1,
            waveAmplitudeScale: 0,
            waveFrequency: 0,
            beamLengthScale: 0,
            beamWidthScale: 0,
            knockback: 7,
            color: "#f97316",
            accentColor: "#fde047",
            splashRadiusScale: 2.1,
            splashDamageScale: 0.9,
          },
        ],
      },
    },
    {
      id: "explosive_ground_wave",
      label: "Ground Wave",
      prompt: "Swing-cast a compact explosive ground wave from the hand.",
      attack: {
        description: "Ground Wave",
        family: "explosive",
        deliveryStyle: "swing",
        palette: { primaryColor: "#fb923c", accentColor: "#fef08a" },
        weaponVisual: { kind: "bomb", primaryColor: "#fb923c", accentColor: "#fef08a", scale: 0.95, handOffsetX: 0.1, handOffsetY: 0 },
        castFx: { color: "#fef08a", accentColor: "#fb923c", count: 9, sizeScale: 0.42, speedScale: 1.5, lifespan: 0.18 },
        actions: [
          {
            type: "projectiles",
            pattern: "ground_wave",
            projectileKind: "flame",
            count: 1,
            speed: 10,
            sizeScale: 0.6,
            spreadDeg: 0,
            damageScale: 0.95,
            lifetimeFrames: 42,
            gravityScale: 0,
            homingStrength: 0,
            orbitFrames: 0,
            orbitRadiusScale: 1,
            waveAmplitudeScale: 0.36,
            waveFrequency: 0.26,
            beamLengthScale: 0,
            beamWidthScale: 0,
            knockback: 6,
            color: "#fb923c",
            accentColor: "#fef08a",
            splashRadiusScale: 0,
            splashDamageScale: 0.7,
          },
        ],
      },
    },
  ],
  summon: [
    {
      id: "summon_orbit_orbs",
      label: "Orbit Orbs",
      prompt: "Swing-cast orbiting orbs that release toward the enemy.",
      attack: {
        description: "Orbit Orbs",
        family: "summon",
        deliveryStyle: "swing",
        palette: { primaryColor: "#34d399", accentColor: "#93c5fd" },
        weaponVisual: { kind: "orb", primaryColor: "#34d399", accentColor: "#93c5fd", scale: 1, handOffsetX: 0.12, handOffsetY: 0 },
        castFx: { color: "#93c5fd", accentColor: "#34d399", count: 8, sizeScale: 0.46, speedScale: 1.4, lifespan: 0.22 },
        actions: [
          {
            type: "projectiles",
            pattern: "orbit",
            projectileKind: "orb",
            count: 3,
            speed: 10,
            sizeScale: 0.48,
            spreadDeg: 0,
            damageScale: 0.8,
            lifetimeFrames: 84,
            gravityScale: 0,
            homingStrength: 0.05,
            orbitFrames: 26,
            orbitRadiusScale: 1.9,
            waveAmplitudeScale: 0,
            waveFrequency: 0,
            beamLengthScale: 0,
            beamWidthScale: 0,
            knockback: 4,
            color: "#34d399",
            accentColor: "#93c5fd",
            splashRadiusScale: 0,
            splashDamageScale: 0.7,
          },
        ],
      },
    },
    {
      id: "summon_spectral_spear",
      label: "Spectral Spear",
      prompt: "Punch-cast a spectral spear with a crisp forward launch.",
      attack: {
        description: "Spectral Spear",
        family: "summon",
        deliveryStyle: "punch",
        palette: { primaryColor: "#10b981", accentColor: "#d1fae5" },
        weaponVisual: { kind: "spear", primaryColor: "#10b981", accentColor: "#d1fae5", scale: 1.05, handOffsetX: 0.14, handOffsetY: 0 },
        castFx: { color: "#d1fae5", accentColor: "#10b981", count: 7, sizeScale: 0.42, speedScale: 1.5, lifespan: 0.18 },
        actions: [
          {
            type: "projectiles",
            pattern: "straight",
            projectileKind: "shard",
            count: 1,
            speed: 12,
            sizeScale: 0.72,
            spreadDeg: 0,
            damageScale: 1,
            lifetimeFrames: 48,
            gravityScale: 0,
            homingStrength: 0.015,
            orbitFrames: 0,
            orbitRadiusScale: 1,
            waveAmplitudeScale: 0,
            waveFrequency: 0,
            beamLengthScale: 0,
            beamWidthScale: 0,
            knockback: 6,
            color: "#10b981",
            accentColor: "#d1fae5",
            splashRadiusScale: 0,
            splashDamageScale: 0.7,
          },
        ],
      },
    },
  ],
};

export function getCuratedAttackPresets(familyId) {
  return CURATED_ATTACK_PRESETS_BY_FAMILY[familyId] || [];
}
